### ISSUE TITLE
Increase possible version range of @ngrx/signals

### ISSUE THREAD

**Issue by Zwergenpunk** [angular-architects/ngrx-toolkit#101]
Currently the version is pinned to exactly 18.1.0. Maybe change the version range to ^18.1.0 or at least ~18.1.0.

thanks for your work! 👍

**Comment by rainerhahnekamp** [comment]
Yes, @Zwergenpunk, we should switch to a more relaxed version range. The current one comes from a time where we were using private APIs. So we had to be careful even with a new patch version. That's not needed anymore.

Btw, do you want to do the PR?

**Comment by Zwergenpunk** [comment]
Hey yeah sure I can do it.

**Comment by rainerhahnekamp** [comment]
I've now just added 18.1.1 so that we can publish but your PR can change that to ^18.1.0
