### ISSUE TITLE
support to clear/reset undoRedo stack in `withUndoRedo`

### ISSUE THREAD

**Issue by LukasSefcik** [angular-architects/ngrx-toolkit#105]
I would like to add support for resetting the stack in certain cases. So I imagine it as adding a reset method that would clear the stack. If this solution sounds good to you, I can prepare a PR.

**Comment by LukasSefcik** [comment]
Clear stack supported via PR #106

**Comment by rainerhahnekamp** [comment]
Fixed with #106
