### ISSUE TITLE
Update entity must be Partial<Entity>

### ISSUE THREAD

**Issue by qooco** [angular-architects/ngrx-toolkit#24]
Update method accepts only full entity, but  usualy update not require it

Plus update calls patchState(store, { [currentKey]: entity }); its problem when entity is Partial<Entity>

Offcourse we can write new method for partial updates...

**Comment by rainerhahnekamp** [comment]
Thanks for reporting @qooco. Do you want to provide a PR as well or should we do it?

**Comment by qooco** [comment]
I will see it depends on time, thanks for answer

**Comment by qooco** [comment]
PR #26
