### ISSUE TITLE
withStorageSync() autoSync not working when selector is provided

### ISSUE THREAD

**Issue by Borja204** [angular-architects/ngrx-toolkit#27]
When you provide a select function, it gets properly saved to the local sotrage but it gets overrided by the initial state when refreshing the app.

Not entiirely sure if its an issue of the extension but only happens when provided a select funcion.

**Comment by Borja204** [comment]
My mistake, was making the slice wrong

**Comment by rainerhahnekamp** [comment]
Alrighty, less work for us ;)
