### ISSUE TITLE
Cannot use `withDevTools` from `@angular-architects/ngrx-toolkit` with `@ngrx/store` and `@ngrx/effects`

### ISSUE THREAD

**Issue by Konadu-Akwasi-Akuoko** [angular-architects/ngrx-toolkit#47]
Hello guys,

I was trying to use the `withDevtools` from the `ngrx-toolkit`, to view my state in Redux Dev Tools like this:

```typescript
export const ThemeStore = signalStore(
  { providedIn: 'root' },
  withDevtools('theme'),
  withState(initialState)
);
```

And inside my `app.config.ts` file I was also using the `provideStore()` and `provideEffects()` from `ngrx`, and I noticed when I used the store and effects from ngrx, the `signalStore` cannot appear in the redux devtools:

![image](https://github.com/angular-architects/ngrx-toolkit/assets/69827203/e83d2bbf-b0ac-46aa-af9c-9c39500db7ed)

But when I removed the `provideStore()` and the `provideEffects()`, from my `app.config.ts` file it worked as expected:

![image](https://github.com/angular-architects/ngrx-toolkit/assets/69827203/2e181567-1ff2-4b82-b9aa-e42d744666ca)

When I read the docs(the README file), there was no explicit statement stating that the `withDevtools` feature from the `@angular-architects/ngrx-toolkit` will not work with the `provideStore()` and the `provideEffects()` feature from ngrx.

I may be wrong in my assessment, and I don't also know if this is the intended behaviour.

All in all, please let me know if this must be explicitly added in the README file, because maybe it is  the intended behaviour, and I'll be happy to add it. Or it is a mistake on my part.

**Comment by rainerhahnekamp** [comment]
Hello, so I use both Signal Store and the Global Store with enabled extensions. DevTools show my my global store but also the Signal Store. That must work.

Your Redux DevTools should give you an option to switch between them. What happens if you click on the select box top right?

<img width="570" alt="Screenshot 2024-05-03 at 14 43 00" src="https://github.com/angular-architects/ngrx-toolkit/assets/5721205/9bb03638-e2c7-4bd0-b548-0485620c4a55">

**Comment by Konadu-Akwasi-Akuoko** [comment]
Thanks a lot @rainerhahnekamp , after I switched it, I saw that it worked. Thanks a lot, for the response. It is now working as expected.

This is with `ngrx/store`:
![image](https://github.com/angular-architects/ngrx-toolkit/assets/69827203/a92f3833-3e47-474d-9654-00e2caf7d4f9)

And this is with `ngrx/signals`:
![image](https://github.com/angular-architects/ngrx-toolkit/assets/69827203/54245c5f-4a89-4f7f-8a27-71fb8bc9b324)

Thanks for clarifying.

I don't know must it be explicitly stated in the docs, or it'll be obvious to others?

**Comment by rainerhahnekamp** [comment]
Great and thanks for letting us know. I think a note in the docs would not hurt.

**Comment by rainerhahnekamp** [comment]
Sure, please go ahead!

**Comment by lordememphis** [comment]
Hi, @Konadu-Akwasi-Akuoko.  Do you mind sharing the exact configuration and setup you did for this to work for you? I'm quite stuck on this myself. I installed the `@angular-architects/ngrx-toolkit` package and configured `withDevtools` in my store (just that), but I'm unable to view my signal store state in Redux Devtools. I also have a global store for `ngrx/store` and `ngrx/effects`.

**Comment by Konadu-Akwasi-Akuoko** [comment]
> Hi, @Konadu-Akwasi-Akuoko. Do you mind sharing the exact configuration and setup you did for this to work for you? I'm quite stuck on this myself. I installed the `@angular-architects/ngrx-toolkit` package and configured `withDevtools` in my store (just that), but I'm unable to view my signal store state in Redux Devtools. I also have a global store for `ngrx/store` and `ngrx/effects`.

Sure sorry for not replying earlier

**Comment by rainerhahnekamp** [comment]
@Konadu-Akwasi-Akuoko just to add: The store might not show up immediately in the devtools, only when the component is rendered the first time that uses it.
