### ISSUE TITLE
When new rc with @ngrx/signals@18.0.0-rc.1

### ISSUE THREAD

**Issue by benzmarkus** [angular-architects/ngrx-toolkit#59]
With angular18 and ngrx/signals i get compile errors because i need --legacy-peer-deps to install all packages, but then i get "Cannot resolve type entity i15.TranslateModule to symbol" during "ng serve".

With direct support of ngrx/signals@18.0.0-rc.1 everything works fine.

**Comment by rainerhahnekamp** [comment]
Hi, can you please check which version of ngrx/signals is running when you perform the --legacy-peer-deps variation?

**Comment by jjs98** [comment]
@rainerhahnekamp I saw you updated to angular 18. Is there going to be a new release?

**Comment by rainerhahnekamp** [comment]
Yes, @jjs98, I'm still running some tests because the internal code base underwent quite a lot of changes.

The new version will only work on rc2, though. An option will also be available if you need support for rc1 and former.

**Comment by jjs98** [comment]
Sounds nice, I cannot wait to try it out ^^

**Comment by rainerhahnekamp** [comment]
@benzmarkus the new version was just released. just install 

- `@ngrx/signals@next` and
-  `@angular-architects/ngrx-toolkit@latest`

@jjs98 please give the new version a try

**Comment by jjs98** [comment]
@rainerhahnekamp I LOVE it!! Thanks for making this!

**Comment by rainerhahnekamp** [comment]
Thanks @jjs98 will pass it on to my colleagues as well
