### ISSUE TITLE
Keep store type in updateState

### ISSUE THREAD

**Issue by brennohv** [angular-architects/ngrx-toolkit#62]
I've noticed that when we use updateState it loses the store type, example:
![image](https://github.com/angular-architects/ngrx-toolkit/assets/84404587/6a1a7832-f702-4a02-ad50-e7a84605005e)

Meanwhile I got around this issue by encapsulating your function like this.
```
import { updateState } from '@angular-architects/ngrx-toolkit';
import { PartialStateUpdater, StateSignal } from '@ngrx/signals';
import { Prettify } from '@ngrx/signals/src/ts-helpers';

export function updateStateLib<State extends object>(
  stateSignal: StateSignal<State>,
  message: string,
  ...updaters: Array<
    Partial<Prettify<State>> | PartialStateUpdater<Prettify<State>>
  >
) {
  updateState(stateSignal, message, ...updaters);
} 
```
![image](https://github.com/angular-architects/ngrx-toolkit/assets/84404587/c6baac16-e2d6-406f-ac3e-45ebe9028268)

**Comment by rainerhahnekamp** [comment]
@brennohv that should fixed, in the latest version. could you please check?

**Comment by brennohv** [comment]
It's fixed
