### ISSUE TITLE
[Bug] withDevtools - non-root store

### ISSUE THREAD

**Issue by begrs** [angular-architects/ngrx-toolkit#63]
If the store is not set as "provide in root" then the devtools will not show the store at all.
No clue why this would be an issue in the implementation yet, but it does not seem to work in our setup. Root stores work just fine. 

I will investigate this myself, too. Just wanted to post the issue immediately to keep track of it for new versions of the withDevtools/updateState developments.

**Comment by rainerhahnekamp** [comment]
@begrs it should show up as soon as you navigate to a component which uses the store - not before. Can you please check?

**Comment by begrs** [comment]
If it is working for you, I will try to supply a code example on monday. It does not work for use. The root store works when navigating to the component (because we use lazy loading routes, even root stores do not initialize before), but the non-root stores did not show up at all.

**Comment by rainerhahnekamp** [comment]
Hey @begrs I just rechecked it and it works in my example. It would be great if you could come up with one on your own.

**Comment by rainerhahnekamp** [comment]
Closing this one. If this issue re-appears don't hesitate and re-open it.
