### ISSUE TITLE
withDevtools Not Updating State for Computed Values in Signal Store

### ISSUE THREAD

**Issue by sharopcha** [angular-architects/ngrx-toolkit#68]
I am using the withDevtools extension from the NgRx Toolkit with my Signal Store. My store includes a computed value using withComputed(). The computed value correctly updates when checked through logging, but these updates do not reflect in the Redux DevTools.

Here is a simplified version of my store setup:

`export const UserStore = signalStore(
  { providedIn: 'root' },
  withDevtools('User Info Store'),
  withState(userState),
  withComputed((store) => ({
    hasSubtenant: computed(() => store.keycloakRoles().includes('HAS_SUBTENANT'))
  })),
);`

**Comment by bvasen** [comment]
@rainerhahnekamp Wouldn't it be nice to also see the computed values as well, so that you can see the whole state of the store at once. 
Is there some other easy workflow for e.g. debugging state changes that are impacting computed values as well?
