### ISSUE TITLE
Build errors with 18.0.2

### ISSUE THREAD

**Issue by caboodal** [angular-architects/ngrx-toolkit#79]
Just added the toolkit ^18.0.2 to my project with @ngrx/signals ^18.0.2 and I get the following build errors after adding withDevtools to a single signalStore.

X [ERROR] TS2307: Cannot find module '@ngrx/store/src/models' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/@angular-architects/ngrx-toolkit/lib/redux-connector/create-redux.d.ts:1:42:
      1 │ import { ActionCreator, ActionType } from "@ngrx/store/src/models";
        ╵                                           ~~~~~~~~~~~~~~~~~~~~~~~~

X [ERROR] TS2307: Cannot find module '@ngrx/store/src/models' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/@angular-architects/ngrx-toolkit/lib/redux-connector/model.d.ts:4:60:
      4 │ ...ctionCreator, ActionType, Prettify } from '@ngrx/store/src/models';
        ╵                                              ~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by caboodal** [comment]
I have added the withDevtools to a global store and it builds fine, I only get the above error for a store I'm using for a component.

**Comment by caboodal** [comment]
OK I need @ngrx/store installed as a dependency as well, is there a document to explain the setup and also what I can achieve with the dev tools?

**Comment by rainerhahnekamp** [comment]
@caboodal, that's a bug. we will make the redux-connector as a second entrypoint. by that, you only need @ngrx/store if you use the connector.

the only documentation so far is the README. there is not so much you can do at the moment. What kind of requirements would you have?

**Comment by caboodal** [comment]
I was keen to be able to visualize the signal store state like I did with the redux pattern, that was incredibly useful. I can't find the Ngrx Devtools extension in the Chrome store to progress any further?

**Comment by rainerhahnekamp** [comment]
@caboodal It is the same Redux extension you use for the Ngrx Devtools. You just add `withDevtools` and the Redux Devtools will show the NgRx Signal Store.

**Comment by caboodal** [comment]
Ah OK I thought I'd tried that, OK no worries I'll take another look.

**Comment by rainerhahnekamp** [comment]
@caboodal did it work?

**Comment by nelkasovic** [comment]
@caboodal Can you do me a favor and check what `compilerOptions -> moduleResolution` in your `tsconfig.json` is set to? I get the same error with `moduleResolution: bundler`. Some other options like `node10` worked fine.

**Comment by caboodal** [comment]
> @caboodal did it work?

Yes it did, I did uninstall it the other day so just reinstalled it and I can now see my state

**Comment by the1979** [comment]
We are getting the same build error (`^18.0.2` versions). We've tried with `moduleResolution` of `"node"` and `"node10"` - no luck.

**Comment by caboodal** [comment]
> @ngrx/store

I installed @ngrx/store as a dependency to make it work, I assume once the bug is resolved we can then remove that superfluous dependency again.

**Comment by caboodal** [comment]
As there seems to be a few responses I've reopened the issue.

**Comment by maniya108** [comment]
Hi Team, We are using angular latest version and ngrx-toolkit as well. In our team also facing the same issue. Attaching the screenshot for reference.
<img width="998" alt="image" src="https://github.com/user-attachments/assets/dca79d68-47f4-433c-ab51-391fe3276bef">

**Comment by rainerhahnekamp** [comment]
@maniya108 sorry for that. the quick workaround is to install @ngrx/store. We will soon have the fix which puts the redux connector as second entry point, meaning, you need @ngrx/store only, if you USE the connector.

**Comment by rainerhahnekamp** [comment]
Starting vom 18.0.3, you should not get any compilation errors anymore.

If you use the redux-connector, you must import it via a secondary entrypoint (see docs) and then you require @ngrx/store.

@maniya108, @caboodal @the1979: can somebody of you confirm that it is now working for you as well? Unfortunately, I was not able to reproduce it.

**Comment by michael-small** [comment]
This seems to be relevant to this issue despite my issue not being about the redux connector:

This update to 18.0.3 allowed me to pull out `@ngrx/store` of the dependencies to get the toolkit working on Stackblitz. No more error like the one in this issue.

**Comment by the1979** [comment]
> Starting vom 18.0.3, you should not get any compilation errors anymore.
> 
> If you use the redux-connector, you must import it via a secondary entrypoint (see docs) and then you require @ngrx/store.
> 
> @maniya108, @caboodal @the1979: can somebody of you confirm that it is now working for you as well? Unfortunately, I was not able to reproduce it.

@rainerhahnekamp I can confirm that `18.0.3` fixes it for us. Thank you!

**Comment by rainerhahnekamp** [comment]
Great, thanks for your quick response!

**Comment by caboodal** [comment]
Hi @rainerhahnekamp 

Everything now building successfully without the need for a dependency on @ngrx/store, many thanks!

Sorry for the slow response, just returned from holiday :-)
