### ISSUE TITLE
Extend withUndoRedo with skip option to skip initial state change

### ISSUE THREAD

**Issue by marcindz88** [angular-architects/ngrx-toolkit#81]
Hi
I want to propose a small feature that is required in my project, which is to allow skipping n first state changes or at least first one as some of the changes at the start are to set up the store and should not be allowed to be undone.

Solution includes extending undoRedoConfig with `skip: number` and adding: 
```typescript
if (normalized.skip > 0) {
  normalized.skip -= 1;
  return;
}

in onInit effect after determining cand

```

**Comment by rainerhahnekamp** [comment]
That's doable. Can you provide a PR along a unit test?

**Comment by marcindz88** [comment]
Yes, I will work on that, however I don't see any tests for this feature, I will try to add some basic ones as well.

**Comment by marcindz88** [comment]
@rainerhahnekamp Hi could you take a look: https://github.com/angular-architects/ngrx-toolkit/pull/83 ?

**Comment by rainerhahnekamp** [comment]
Thanks @marcindz88
