### ISSUE TITLE
Document usage of withDevtools(): No store found.

### ISSUE THREAD

**Issue by thomas-bee** [angular-architects/ngrx-toolkit#90]
Please add more documentation on how to use `withDevtools()`. Just throwing in `withDevtools('flights')` then using the latest Chrome with the latest Redux DevTools 

https://chromewebstore.google.com/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=de  

... simply results in the store window saying "No store found". Please document the required steps to make this work.

**Comment by rainerhahnekamp** [comment]
There you go #93. Does that help?

**Comment by rainerhahnekamp** [comment]
Docs have been improved
