### ISSUE TITLE
Update peerDependencies related to @ngrx/signals": "18.1.0"

### ISSUE THREAD

**Issue by mlc-mlapis** [angular-architects/ngrx-toolkit#98]
Is it possible to update **peerDependencies** to reflect the latest version of  `@ngrx/signals": "18.1.0"`? Thanks.

The actual setting:
```
"peerDependencies": {
    "@ngrx/signals": "18.0.2",
    "@ngrx/store": ">=18.0.0"
},
```

**Comment by geokaps** [comment]
I second that. Thanks!

**Comment by rainerhahnekamp** [comment]
Oooops. Sorry for that. Completely missed it.

**Comment by rainerhahnekamp** [comment]
Done
